### ISSUE TITLE
Twitter next version support

### ISSUE THREAD

**Issue by andypiper** [spatie/twitter-labs#1]
Hello from Twitter Developer Relations!

First of all: Thank You, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around! In a recent survey I conducted, PHP was a very high usage language, so we do understand that very many web and PHP developers want to interact on Twitter.

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs to twitter-lite! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI. One thing I unfortunately cannot offer, and I know we already spoke about on Twitter, is a change to data volumes on streams - but it's something I'll continue to champion for you if I can.

Thank you again for building for our platform.

**Comment by AlexVanderbist** [comment]
Hi @andypiper, thanks for checking in! We've already added support for annotations and are looking forward to future developments of your new API :) 

>I would love to connect with you on any plans to add support for Twitter Developer Labs to twitter-lite!

Bad copy paste? 😅
